### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by mtehonica** [t0nyz0/BambuBoard#12]
Currently, running BambuBoard behind a reverse proxy with SSL will result in nothing being displayed and a bunch of errors in the console.

![image](https://github.com/user-attachments/assets/582949a9-02ba-41ed-93bb-7ff16a3a4b67)

**Comment by t0nyz0** [comment]
Test out this new version (v1.1.1) when you get a minute.

**Comment by mtehonica** [comment]
That was quick! Just tested and appears to be working perfectly!

![image](https://github.com/user-attachments/assets/3be42edc-74dd-4ab2-a3d1-5f31120d7276)

**Comment by t0nyz0** [comment]
Another win! This was an easy one.
